# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-14 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('c_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-c_time',),
            },
        ),
    ]
